### ISSUE TITLE
Testing milestone

### ISSUE THREAD

**Issue by jamesdavis12** [SCCapstone/CapiStonsker#183]
Check out the [Testing Page](https://capstone.cse.sc.edu/milestone/testing/) for instructions, milestone due Sun Jan 30th.

Let's create 1 behavioral and 1 unit test each by the deadline to familiarize ourselves with testing and get ahead for the second testing deadline.

Tests should go in a folder called `tests`
- [x] Create `tests` folder (whoever starts working first can do this)

Checklist for each of us:
@jamesdavis12 
- [x] Create a unit test & push to GitHub
- [ ] Create a behavioral test & push to GitHub
- [ ] Push release to GitHub once all tests are made

@MattyD797 
- [ ] Create a unit test & push to GitHub
- [ ] Create a behavioral test & push to GitHub
- [x] Add a Testing section to the readme (see the [milestone page](https://capstone.cse.sc.edu/milestone/testing/))

@Urton-Ian28 
- [x] Create a unit test & push to GitHub
- [ ] Create a behavioral test & push to GitHub

@lehodges511 
- [ ] Create a unit test & push to GitHub
- [ ] Create a behavioral test & push to GitHub

@JoeCamm 
- [ ] Create a unit test & push to GitHub
- [ ] Create a behavioral test & push to GitHub
