### ISSUE TITLE
Testing checklist

### ISSUE THREAD

**Issue by jamesdavis12** [SCCapstone/CapiStonsker#308]
### Deliverables (from the [testing milestone page](https://capstone.cse.sc.edu/milestone/testing/))
- [x] #300 
- [x] #309 Test the core functionality of the app.
- [x] In your Readme.md file add a Testing section which lists the commands/instructions one must type to run your tests the directory (or filename regexep) where all your tests are located
- [x] Update Readme with instructions for running all tests
- [x] Add an Issue titled "Testing Video" to your repo and put in there a video, or more, showing how the tests run.
- [ ] **Optionally**, set up a continuous integration service, like [travis](http://travis-ci.com/) to automatically run your tests.

**Comment by jamesdavis12** [comment]
@josemvidal Do we need to show all of our tests in the testing video?

**Comment by josemvidal** [comment]
Yes, show it running the full test suite.
