### ISSUE TITLE
Source control milestone

### ISSUE THREAD

**Issue by jamesdavis12** [SCCapstone/CapiStonsker#46]
From the [source control milestone page](https://capstone.cse.sc.edu/milestone/source-control/):

The goal of this milestone is to ensure everything is set up correctly, and the whole team has started working together on their app using a shared codebase, with everything in git. The codebase does not need to do much, but it should at least include your framework. For example, if you are building an Android app then the codebase should be an Android app.

# TODO
- [x] Complete team checklist (see comment below)
- [x] Complete individual checklist for @jamesdavis12 (see comment below)
- [x] Complete individual checklist for @MattyD797 (see comment below)
- [x] Complete individual checklist for @Urton-Ian28 (see comment below)
- [x] Complete individual checklist for @JoeCamm (see comment below)
- [x] Complete individual checklist for @lehodges511 (see comment below)
